import 'dart:typed_data';

import 'package:excel/excel.dart' as xl;

import '../../domain/entities/data_element_entity.dart';

/// Builds a downloadable snapshot of a data entry form as an XLSX
/// workbook — one flat, sortable table (Data Element, Category, Value)
/// rather than the PDF's grouped/printable layout, since that's the
/// shape spreadsheets are actually used for. Same source data as
/// [buildDataEntryPdf] (see data_entry_pdf.dart): built entirely from
/// what's already loaded on screen, so it works offline too.
Uint8List buildDataEntryExcel({
  required String title,
  required String orgUnitName,
  required String periodLabel,
  required bool isDiseaseRegistration,
  required List<DataElementEntity> dataElements,
  required Map<String, DataValueEntity> dataValues,
  String? printedBy,
}) {
  const sheetName = 'Data';
  final workbook = xl.Excel.createExcel();
  final sheet = workbook[sheetName];
  // Excel.createExcel() always seeds a default "Sheet1" — drop it once
  // our named sheet exists so the file doesn't ship an empty tab.
  for (final name in List<String>.from(workbook.sheets.keys)) {
    if (name != sheetName) workbook.delete(name);
  }

  var row = 0;
  void writeLine(String text, {bool bold = false}) {
    final cell = sheet
        .cell(xl.CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row));
    cell.value = xl.TextCellValue(text);
    if (bold) cell.cellStyle = xl.CellStyle(bold: true);
    row++;
  }

  writeLine(title, bold: true);
  if (isDiseaseRegistration) writeLine('Disease Registration');
  writeLine('$orgUnitName  ·  $periodLabel');
  if (printedBy != null && printedBy.isNotEmpty) {
    writeLine('Generated by $printedBy');
  }
  row++; // blank separator row before the table

  const headers = ['Data Element', 'Category', 'Value'];
  for (var col = 0; col < headers.length; col++) {
    sheet
        .cell(xl.CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
      ..value = xl.TextCellValue(headers[col])
      ..cellStyle = xl.CellStyle(bold: true);
  }
  row++;

  for (final element in dataElements) {
    for (final combo in element.categoryOptionCombos) {
      sheet
          .cell(xl.CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: row))
          .value = xl.TextCellValue(element.displayName);
      sheet
          .cell(xl.CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: row))
          .value = xl.TextCellValue(combo.displayName);
      sheet
          .cell(xl.CellIndex.indexByColumnRow(columnIndex: 2, rowIndex: row))
          .value = xl.TextCellValue(_valueOf(dataValues, element.id, combo.id));
      row++;
    }
  }

  sheet
    ..setColumnWidth(0, 36)
    ..setColumnWidth(1, 28)
    ..setColumnWidth(2, 16);

  return Uint8List.fromList(workbook.encode() ?? const []);
}

String _valueOf(
    Map<String, DataValueEntity> dataValues, String elementId, String comboId) {
  final v = dataValues['${elementId}_$comboId']?.value.trim() ?? '';
  return v.isEmpty ? '—' : v;
}
